url: "https://github.com/page-bird/jekyll-theme-page-bird"
page_bird:
  website_id: "42321225"
  popup:
    active: true
    exclude_pages: ["thanks"]
  seo:
    title: "Jekyll Theme Page Bird"
    description: "This is the default theme Page Bird uses for its websites."
    image_url: ""
    locale: "en_US"
  blog:
    sharing: true
    share_facebook: true
    share_twitter: true
    share_linkedin: true
  api_host: "http://localhost:3000" # Use localhost only for testing purposes. Else, delete this line.
